### ISSUE TITLE
Portfolio: application deploy

### ISSUE THREAD

**Issue by alvaroiporre** [alvaroiporre/My-Portfolio#8]
I deployed my app earlier, this is the link to the online version of my [project](https://alvaroiporre.github.io/My-Portfolio/).

**Comment by adel-gu** [comment]
# Status: APPROVED 🟢 

**Hi @alvaroiporre 👋🏼** 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media0.giphy.com/media/ZdUnQS4AXEl1AERdil/giphy.gif?cid=ecf05e47wnzv8arl0nlv7d0z7cnajxze9kxu2w95q10ydzv2&rid=giphy.gif&ct=g)

## Highlights
- Used GitHub pages ✅ 
- Live demo link is working ✅ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
